/-
  # Correctness of `src/lib.rs::modinverse_u128`, in three layers

  > Generated by AI (Claude). The Lean kernel checks the proofs; the *translation*
  > from Rust to Lean (in `ModInverse/Model.lean`) is by inspection for now, and is
  > slated to be replaced by an Aeneas-extracted model.

  This development is split so that *what correctness means* and *the proof that
  the code achieves it* are maintained separately:

    ┌─ ModInverse/Model.lean ─── the algorithm (ℕ translation of the Rust;
    │                            definitions only; later Aeneas-generated)
    │
    ├─ ModInverse/Targets.lean ─ HUMAN-MAINTAINED - the specification: what it
    │                            means to be a correct modular inverse, as a
    │                            `structure` parameterized by the model. Read only
    │                            this file to judge whether "correct" is the right
    │                            notion.
    │
    └─ ModInverse/Proofs.lean ── AI-MAINTAINED - the proofs, ending in
                                 certificates `isCorrect : Spec.Correct modinverse`
                                 and `helpersCompute : Spec.HelpersCompute …`.

  The link between the bottom two layers is mechanical: a certificate is a
  `structure` instance, so it fails to typecheck unless *every* target field is
  discharged with a term of exactly the declared type. Targets cannot be silently
  dropped or weakened, and adding a target forces a new proof.

  The four behavioural targets together pin down `modinverse` on every input:
  soundness (a returned witness is a real inverse), bound (`0 ≤ s < m`),
  completeness (an inverse is returned whenever one exists), and exact failure
  (`none` exactly otherwise). Two further targets state that the overflow-avoiding
  `addMod`/`mulMod` helpers compute ordinary `(a+b) % m` and `(a*b) % m`.
-/

import ModInverse.Model
import ModInverse.Targets
import ModInverse.Proofs
