/-
  # Correctness proof for `src/lib.rs::modinverse_u128`

  > This file was generated by AI (Claude Opus 4.7) and has not been
  > independently reviewed by a human proof author. The Lean kernel checks
  > the proofs; the *translation* from Rust to Lean is by inspection only.

  This file defines, in Lean 4 + Mathlib, the same algorithm as the Rust
  function `modinverse_u128` in `src/lib.rs`, and proves four theorems about
  it: soundness (the returned `s` really is a modular inverse), a bound
  (`0 ≤ s < m`), completeness (an inverse is returned whenever one exists),
  and a no-false-positives result (`none` is returned otherwise). The four
  theorems together pin down the function's behaviour on every input.

  The two `mulMod` / `addMod` helpers also have their algorithm-level
  correctness proved (`mulMod_eq`, `addMod_eq`) — i.e. that the Russian-
  peasant and "room" routines compute `(a*b) % m` and `(a+b) % m`
  respectively. The remaining "and the Rust `u128` operations behave that
  way under the documented preconditions" claim is by inspection.

  The algorithm runs the extended Euclidean algorithm with one unusual twist:
  it reduces the Bézout-style coefficient modulo `m` at *every* iteration,
  keeping `s` and `sNext` in `[0, m)` throughout. Every published treatment
  (Wikipedia, cp-algorithms, CLRS, Mathlib's own `Nat.xgcdAux`) carries
  signed coefficients over `ℤ` and reduces once at the end. The per-step
  reduction is what allows the Rust implementation to run on *unsigned*
  integer types without ever producing a negative intermediate. The
  conceptual fix — "use modular reduction to keep coefficients non-negative,
  returning Bézout-style coefficients in `[0, m)`" — was sketched by
  @electraminer in a comment on issue #2 ("modinverse panics on unsigned
  integer types"):
  https://github.com/simon-andrews/rust-modinverse/issues/2#issuecomment-1846695734
  The concrete iterative algorithm in `src/lib.rs`, this Lean translation,
  and the proofs below were generated by Claude Opus 4.7. No prior written
  proof of correctness for this variant of extended Euclid could be found —
  the per-step reduction appears to be a folklore trick — which is why I had
  Claude prove it was correct.

  ## How this connects to the Rust code

  The Lean definitions below are a hand translation of the Rust code in
  `src/lib.rs`. The mapping is intentionally one-to-one:

      Rust                              Lean
      ────────────────────────────      ────────────────────────────
      fn sub_mod_u128(a, b, m)          def subMod (a b m : ℕ)
      fn add_mod_u128(a, b, m)          def addMod (a b m : ℕ)
      fn mul_mod_u128(a, b, m)          def mulMod (a b m : ℕ)
      one loop iteration                def step
      `while r_next != 0 { ... }`       def loop  (well-founded recursion)
      fn modinverse_u128(a, m)          def modinverse

  Differences worth flagging:

    * Rust is `u128`; Lean works in `ℕ`. The `u128` operations used by the
      Rust code never overflow under their preconditions (see the comments
      on each helper), so a `ℕ` model captures the relevant semantics.

    * Rust's `while !r_next.is_zero()` loop becomes a recursive `def loop`
      that decreases on `rNext`. Same control flow, different syntax.

  So the bridge from these theorems to a guarantee about the Rust code is:
  *if the translation faithfully mirrors the Rust* (verifiable by inspection),
  *then* the Rust code satisfies the same four properties.

  ## Mathlib facts used

    * `ZMod m` — the integers mod `m`. Stating the invariant in `ZMod m` means
      modular reductions just disappear; no need to track `% m` by hand.
    * `Nat.gcd_rec : Nat.gcd m n = Nat.gcd (n % m) m` — Euclid's step.
    * `ZMod.natCast_eq_natCast_iff : (↑a = ↑b : ZMod m) ↔ a ≡ b (mod m)` —
      the bridge from `ZMod` equations to `Nat`-level congruences.
-/

import Mathlib.Data.Nat.GCD.Basic
import Mathlib.Data.Int.GCD
import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic

namespace ModInverse

/-! ## `subMod`: subtraction in `[0, m)`

    Same trick as the Rust `sub_mod` helper (`src/lib.rs`): if `a ≥ b`, return
    `a - b`; otherwise add `m` first so the natural-number subtraction is
    well-defined.
-/

/-- Lean mirror of Rust `fn sub_mod_u128(a, b, m)` in `src/lib.rs`. The Rust shape is
    `if a >= b { a - b } else { (m - b) + a }`; the Lean shape `m + a - b` is the same value in
    ℕ but doesn't matter for overflow here (ℕ has no overflow). The Rust shape is chosen so the
    `else` branch stays below `u128::MAX` given `b ≤ m`. -/
def subMod (a b m : ℕ) : ℕ :=
  if a ≥ b then a - b else m + a - b

lemma subMod_lt {a b m : ℕ} (ha : a < m) (hb : b < m) : subMod a b m < m := by
  unfold subMod; split <;> omega

/-- The whole reason `subMod` exists: in `ZMod m`, it's literally `a - b`. -/
lemma subMod_cast (a b m : ℕ) (hb : b < m) :
    ((subMod a b m : ℕ) : ZMod m) = (a : ZMod m) - (b : ZMod m) := by
  unfold subMod
  split
  case isTrue h =>
    rw [Nat.cast_sub h]
  case isFalse h =>
    -- a < b ≤ m, so m + a - b is non-negative, and `m` vanishes in `ZMod m`.
    have hba : b ≤ m + a := by omega
    rw [Nat.cast_sub hba, Nat.cast_add, ZMod.natCast_self, zero_add]

/-! ## Algorithm

    Mirrors `src/lib.rs::modinverse` line-by-line. The Rust code is a `while`
    loop; here the same loop is phrased as a recursive function that decreases
    on `rNext` (the standard way to define this kind of loop in Lean).
-/

/-- Loop state. The two `< m` bounds carry the fact that `s` and `sNext`
    are kept reduced. -/
structure State (m : ℕ) where
  r       : ℕ
  rNext   : ℕ
  s       : ℕ
  sNext   : ℕ
  sLt     : s < m
  sNextLt : sNext < m

/-- One iteration of the loop body in Rust `modinverse_u128`:
    `let (q, rem) = r.div_rem(&r_next);`
    `let qs = mul_mod_u128(q, s_next, m);`
    `(s, s_next) = (s_next, sub_mod_u128(s, qs, m));`
    `(r, r_next) = (r_next, rem);`

    The Lean `step` uses plain ℕ multiplication and `%` for `qs`, and `subMod`
    for the update. This is sound because `mulMod_eq` proves the Russian-
    peasant `mulMod` equals `(a*b) % m`, and `subMod_cast` proves Lean's
    `subMod` matches `sub_mod_u128`'s `(a - b) mod m`. The Rust helpers exist
    only to avoid `u128` overflow; in ℕ those concerns vanish. -/
def step {m : ℕ} (hm : 0 < m) (st : State m) (_hRNext : st.rNext ≠ 0) :
    State m :=
  let qs := (st.r / st.rNext * st.sNext) % m
  { r       := st.rNext
    rNext   := st.r % st.rNext
    s       := st.sNext
    sNext   := subMod st.s qs m
    sLt     := st.sNextLt
    sNextLt := subMod_lt st.sLt (Nat.mod_lt _ hm) }

/-- The `while !r_next.is_zero()` loop, expressed as well-founded recursion.
    Runs `step` until `rNext = 0`, then returns `(r, s)` — the gcd and the
    inverse candidate. Terminates because `rNext` strictly decreases (each
    iteration replaces it with `r % rNext`). -/
def loop {m : ℕ} (hm : 0 < m) : State m → ℕ × ℕ
  | st =>
    if h : st.rNext = 0 then
      (st.r, st.s)
    else
      have : (step hm st h).rNext < st.rNext :=
        Nat.mod_lt _ (Nat.pos_of_ne_zero h)
      loop hm (step hm st h)
  termination_by st => st.rNext

/-- Lean mirror of the inverse computation when `1 < m`. The full Rust
    `modinverse` (which also handles `m = 0` and `m = 1`) is built on top
    of this as `modinverse` below. -/
def modinverseCore (a m : ℕ) (hm : 1 < m) : Option ℕ :=
  let init : State m :=
    { r := m, rNext := a % m, s := 0, sNext := 1,
      sLt := by omega, sNextLt := hm }
  let (gcd, s) := loop (by omega) init
  if gcd = 1 then some s else none

/-- Lean mirror of Rust `pub fn modinverse_u128(a, m) -> Option<u128>`. Handles
    the two early-return cases (`m = 0` → `none`, `m = 1` → `some 0`) and
    delegates the interesting case `1 < m` to `modinverseCore`. -/
def modinverse (a m : ℕ) : Option ℕ :=
  if hm : 1 < m then modinverseCore a m hm
  else if m = 1 then some 0
  else none

/-! ## The loop invariant

    The invariant captures what the algorithm is *doing*: at every step, `s`
    is a "modular witness" for `r`, meaning `a * s ≡ r (mod m)`. Likewise
    `sNext` witnesses `rNext`. When the loop terminates (`rNext = 0`), the
    fact that `r` equals the gcd plus the invariant `a * s ≡ r` is exactly
    what is needed.

    The invariant is stated in `ZMod m` (Mathlib's "integers modulo `m`"
    quotient ring) rather than with `%`: in `ZMod m`, equations are just
    equations, and lemmas like `ring` and `linear_combination` work without
    fighting `%`-arithmetic.
-/

def Invariant (a m : ℕ) (st : State m) : Prop :=
  ((a : ZMod m) * st.s = (st.r : ZMod m)) ∧
  ((a : ZMod m) * st.sNext = (st.rNext : ZMod m))

/-- Loop entry satisfies the invariant.

    * For the first conjunct: `a * 0 = 0`, and `m = 0` in `ZMod m`. ✓
    * For the second: `a * 1 = a`, which equals `a % m` in `ZMod m`. ✓
-/
lemma invariant_init {a m : ℕ} (hm : 1 < m) :
    Invariant a m
      { r := m, rNext := a % m, s := 0, sNext := 1,
        sLt := by omega, sNextLt := hm } := by
  refine ⟨?_, ?_⟩
  · show (a : ZMod m) * (0 : ℕ) = (m : ZMod m)
    simp
  · show (a : ZMod m) * (1 : ℕ) = ((a % m : ℕ) : ZMod m)
    simp [ZMod.natCast_mod]

/-- One iteration preserves the invariant.

    This is the heart of the proof. Let `q = r / rNext`. After one step:

      r'      = rNext              (just a relabeling)
      rNext'  = r % rNext          (the new remainder)
      s'      = sNext              (just a relabeling)
      sNext'  = subMod s ((q*sNext) % m) m

    The first three conjuncts (`r' = rNext`, `s' = sNext`, etc.) make the new
    `a * s' = r'` equation fall out of the old `a * sNext = rNext`. The
    interesting bit is `a * sNext' = rNext'`. In `ZMod m`:

      a * sNext'  = a * (s - q*sNext)         [by `subMod_cast`]
                  = a*s - q*(a*sNext)         [distributing]
                  = r - q*rNext               [by the old invariant]
                  = r % rNext = rNext'        [since r = q*rNext + r%rNext]

    The mod-`m` reductions sprinkled through the Rust code all become no-ops
    in `ZMod m` — that's exactly why the invariant is stated there. -/
lemma invariant_step {a m : ℕ} (hm : 0 < m) (st : State m)
    (hRNext : st.rNext ≠ 0) (hInv : Invariant a m st) :
    Invariant a m (step hm st hRNext) := by
  obtain ⟨h_s, h_sNext⟩ := hInv
  refine ⟨?_, ?_⟩
  · -- After step, `s' = sNext` and `r' = rNext`, so this is just `h_sNext`.
    exact h_sNext
  · -- The new-`sNext = rNext` claim. Set `q := r / rNext` and unfold.
    set q := st.r / st.rNext
    show (a : ZMod m) * (subMod st.s ((q * st.sNext) % m) m : ℕ)
       = ((st.r % st.rNext : ℕ) : ZMod m)
    -- Step 1: in `ZMod m`, the inner `% m` and `subMod` both vanish.
    have hqs_lt : (q * st.sNext) % m < m := Nat.mod_lt _ hm
    rw [subMod_cast _ _ _ hqs_lt]
    have h_qs_cast : (((q * st.sNext) % m : ℕ) : ZMod m)
                  = q * (st.sNext : ZMod m) := by
      rw [ZMod.natCast_mod]; push_cast; ring
    rw [h_qs_cast]
    -- Goal now: a * (s - q*sNext) = r % rNext   (in ZMod m).
    -- Step 2: massage the LHS into `a*s - q*(a*sNext)`, then substitute.
    have h_lhs : (a : ZMod m) * ((st.s : ZMod m) - q * (st.sNext : ZMod m))
               = (a : ZMod m) * st.s - q * ((a : ZMod m) * st.sNext) := by ring
    rw [h_lhs, h_s, h_sNext]
    -- Goal now: r - q*rNext = r % rNext   (in ZMod m).
    -- Step 3: this is just `r = q*rNext + r%rNext` rearranged.
    have h_div_mod : (st.r : ZMod m)
                   = q * (st.rNext : ZMod m) + ((st.r % st.rNext : ℕ) : ZMod m) := by
      have : st.r = st.r / st.rNext * st.rNext + st.r % st.rNext :=
        (Nat.div_add_mod' st.r st.rNext).symm
      calc (st.r : ZMod m)
          = ((st.r / st.rNext * st.rNext + st.r % st.rNext : ℕ) : ZMod m) := by
            rw [← this]
        _ = q * (st.rNext : ZMod m) + ((st.r % st.rNext : ℕ) : ZMod m) := by
            push_cast; ring
    linear_combination h_div_mod

/-! ## Induction over the loop

    Lean's well-founded recursion machinery auto-generates an induction
    principle `loop.induct` with two cases:

      * `case1 x _alias hZero`        — `x.rNext = 0`, the base case.
      * `case2 x _alias hNZ _decr ih` — `x.rNext ≠ 0`, with IH `ih` on the
                                        recursive call.

    The mysterious `_alias` binder is the auto-generated `have st := x` Lean
    inserts so the case bodies can refer to `st` directly. It's not used or
    referenced by name below.
-/

/-- Termination + induction yields the invariant at the loop's *exit*. -/
lemma invariant_loop {a m : ℕ} (hm : 0 < m) (st : State m)
    (hInv : Invariant a m st) :
    (a : ZMod m) * (loop hm st).2 = ((loop hm st).1 : ZMod m) := by
  induction st using loop.induct (m := m) hm with
  | case1 _x _alias hZero =>
    rw [loop, dif_pos hZero]
    exact hInv.1
  | case2 x _alias hNZ _decr ih =>
    rw [loop, dif_neg hNZ]
    exact ih (invariant_step hm x hNZ hInv)

/-- The `s` component stays in `[0, m)` throughout the loop. -/
lemma loop_snd_lt {m : ℕ} (hm : 0 < m) (st : State m) :
    (loop hm st).2 < m := by
  induction st using loop.induct (m := m) hm with
  | case1 x _alias hZero =>
    rw [loop, dif_pos hZero]; exact x.sLt
  | case2 _x _alias hNZ _decr ih =>
    rw [loop, dif_neg hNZ]; exact ih

/-- The loop computes `Nat.gcd`. This is the *classical* Euclidean termination
    statement; it's independent of the `s`/`sNext` business. -/
lemma loop_fst_eq_gcd {m : ℕ} (hm : 0 < m) (st : State m) :
    (loop hm st).1 = Nat.gcd st.r st.rNext := by
  induction st using loop.induct (m := m) hm with
  | case1 x _alias hZero =>
    rw [loop, dif_pos hZero]
    show x.r = Nat.gcd x.r x.rNext
    rw [show x.rNext = 0 from hZero, Nat.gcd_zero_right]
  | case2 x _alias hNZ _decr ih =>
    rw [loop, dif_neg hNZ, ih]
    -- After step, `r = x.rNext` and `rNext = x.r % x.rNext`. So the goal is:
    --   gcd x.rNext (x.r % x.rNext) = gcd x.r x.rNext
    -- That's Euclid's `gcd_rec`, with two `gcd_comm` rewrites for orientation.
    show Nat.gcd x.rNext (x.r % x.rNext) = Nat.gcd x.r x.rNext
    rw [Nat.gcd_comm x.rNext (x.r % x.rNext), ← Nat.gcd_rec, Nat.gcd_comm]

/-! ## Correctness theorems

    These all share the same opening move: introduce the initial state and the
    loop's output, then reason about the `if gcd = 1` branch in `modinverse`.
    The helper `modinverse_dest` packages that opening into one lemma so each
    theorem can focus on its own claim.
-/

/-- Unfold `modinverseCore` once and expose the loop's output. -/
private lemma modinverseCore_dest (a m : ℕ) (hm : 1 < m) :
    let init : State m :=
      ⟨m, a % m, 0, 1, by omega, hm⟩
    let p := loop (by omega) init
    modinverseCore a m hm = if p.1 = 1 then some p.2 else none := rfl

/-- **Soundness** for `modinverseCore`. If it returns `some s`, then `s` really
    is a modular inverse: `a * s ≡ 1 (mod m)`. -/
theorem modinverseCore_correct (a m : ℕ) (hm : 1 < m) (s : ℕ)
    (h : modinverseCore a m hm = some s) :
    a * s % m = 1 := by
  -- Set up the same `init` and `p` that `modinverse` uses internally.
  set init : State m := ⟨m, a % m, 0, 1, by omega, hm⟩ with hinit
  set p := loop (by omega : 0 < m) init with hp
  -- The invariant carries through to the loop's exit.
  have hInvFinal : (a : ZMod m) * (p.2 : ℕ) = ((p.1 : ℕ) : ZMod m) :=
    invariant_loop (by omega) init (invariant_init hm)
  -- From `h`, the gcd was 1 and `s = p.2` (Lean substitutes `s := p.2` below).
  rw [modinverseCore_dest a m hm, ← hinit, ← hp] at h
  split_ifs at h with hgcd
  obtain rfl : p.2 = s := Option.some_inj.mp h
  -- Substitute `p.1 = 1` into the invariant, then translate `ZMod` to `% m`.
  rw [hgcd, Nat.cast_one] at hInvFinal
  have hCast : ((a * p.2 : ℕ) : ZMod m) = ((1 : ℕ) : ZMod m) := by
    push_cast; exact hInvFinal
  rw [ZMod.natCast_eq_natCast_iff, Nat.ModEq, Nat.mod_eq_of_lt hm] at hCast
  exact hCast

/-- **Bound** for `modinverseCore`. The returned witness sits in `[0, m)`. -/
theorem modinverseCore_lt (a m : ℕ) (hm : 1 < m) (s : ℕ)
    (h : modinverseCore a m hm = some s) :
    s < m := by
  set init : State m := ⟨m, a % m, 0, 1, by omega, hm⟩ with hinit
  set p := loop (by omega : 0 < m) init with hp
  have hBound : p.2 < m := loop_snd_lt (by omega) init
  rw [modinverseCore_dest a m hm, ← hinit, ← hp] at h
  split_ifs at h
  obtain rfl : p.2 = s := Option.some_inj.mp h
  exact hBound

/-- A small bridge: the loop's first output is `gcd a m`. -/
private lemma loop_fst_eq_gcd_init {a m : ℕ} (hm : 1 < m) :
    (loop (by omega : 0 < m)
       (⟨m, a % m, 0, 1, by omega, hm⟩ : State m)).1 = Nat.gcd a m := by
  rw [loop_fst_eq_gcd]
  show Nat.gcd m (a % m) = Nat.gcd a m
  -- gcd m (a%m) = gcd (a%m) m = gcd a m, by comm + Euclid step (run backwards).
  rw [Nat.gcd_comm m (a % m), ← Nat.gcd_rec, Nat.gcd_comm]

/-- **Completeness** for `modinverseCore`. If `gcd a m = 1`, it produces an
    inverse. -/
theorem modinverseCore_complete (a m : ℕ) (hm : 1 < m)
    (hCoprime : Nat.Coprime a m) :
    ∃ s, modinverseCore a m hm = some s := by
  set init : State m := ⟨m, a % m, 0, 1, by omega, hm⟩ with hinit
  set p := loop (by omega : 0 < m) init with hp
  have hGcd : p.1 = 1 := by rw [hp]; exact (loop_fst_eq_gcd_init hm).trans hCoprime
  refine ⟨p.2, ?_⟩
  rw [modinverseCore_dest a m hm, ← hinit, ← hp, if_pos hGcd]

/-- **No false positives** for `modinverseCore`. If `a` and `m` aren't coprime,
    the function returns `none`. -/
theorem modinverseCore_none_of_not_coprime (a m : ℕ) (hm : 1 < m)
    (hNotCoprime : ¬ Nat.Coprime a m) :
    modinverseCore a m hm = none := by
  set init : State m := ⟨m, a % m, 0, 1, by omega, hm⟩ with hinit
  set p := loop (by omega : 0 < m) init with hp
  have hGcdNe : p.1 ≠ 1 := by
    rw [hp, loop_fst_eq_gcd_init hm]; exact hNotCoprime
  rw [modinverseCore_dest a m hm, ← hinit, ← hp, if_neg hGcdNe]

/-! ## Wrapper-level theorems

    The four theorems above pin down the behaviour of `modinverseCore` for
    `1 < m`. The four below extend each to the total function `modinverse`,
    handling the `m = 0` and `m = 1` early-return branches that the Rust
    `modinverse_u128` ships with.
-/

/-- **Soundness.** If `modinverse a m = some s`, then `a * s ≡ 1 (mod m)`. -/
theorem modinverse_correct (a m s : ℕ)
    (h : modinverse a m = some s) :
    a * s ≡ 1 [MOD m] := by
  unfold modinverse at h
  split_ifs at h with hm hm1
  · -- 1 < m: defer to modinverseCore_correct.
    have hCore := modinverseCore_correct a m hm s h
    -- a * s % m = 1 and 1 < m, so 1 % m = 1.
    rw [Nat.ModEq, Nat.mod_eq_of_lt hm, hCore]
  · -- m = 1: both sides reduce to 0 mod 1.
    subst hm1
    exact Nat.modEq_one

/-- **Bound.** For `0 < m`, the returned witness sits in `[0, m)`. -/
theorem modinverse_lt (a m s : ℕ) (hm : 0 < m)
    (h : modinverse a m = some s) :
    s < m := by
  unfold modinverse at h
  split_ifs at h with h1 h2
  · exact modinverseCore_lt a m h1 s h
  · -- m = 1, s = 0.
    subst h2
    have : s = 0 := Option.some_inj.mp h.symm
    omega

/-- **Completeness.** For `0 < m`, if `gcd a m = 1`, the function produces
    some inverse. -/
theorem modinverse_complete (a m : ℕ) (hm : 0 < m)
    (hCoprime : Nat.Coprime a m) :
    ∃ s, modinverse a m = some s := by
  unfold modinverse
  split_ifs with h1 h2
  · exact modinverseCore_complete a m h1 hCoprime
  · exact ⟨0, rfl⟩
  · omega

/-- **No false positives.** `modinverse a m = none` iff `m = 0` or `a` and `m`
    are not coprime. -/
theorem modinverse_none_iff (a m : ℕ) :
    modinverse a m = none ↔ m = 0 ∨ ¬ Nat.Coprime a m := by
  unfold modinverse
  constructor
  · intro h
    split_ifs at h with h1 h2
    · -- 1 < m and core returned none. Rule out m=0; show not coprime.
      right
      by_contra hCop
      obtain ⟨s, hs⟩ := modinverseCore_complete a m h1 hCop
      rw [hs] at h
      simp at h
    · -- The `m = 1` branch is closed automatically (`some 0 ≠ none`).
      -- The remaining branch is `¬ 1 < m, ¬ m = 1`, i.e. `m = 0`.
      left; omega
  · intro h
    split_ifs with h1 h2
    · -- 1 < m, so m ≠ 0 and we need not-coprime.
      rcases h with hm0 | hNot
      · omega
      · exact modinverseCore_none_of_not_coprime a m h1 hNot
    · -- m = 1, so a and m are coprime (Nat.Coprime a 1).
      subst h2
      rcases h with hm0 | hNot
      · exact absurd hm0 (by decide)
      · exact absurd (Nat.coprime_one_right a) hNot
    · rfl

/-! ## Helper algorithms: modular addition and multiplication

    The Rust implementation uses two helpers (`add_mod_u128`,
    `mul_mod_u128`) to compute `(a + b) % m` and `(a * b) % m` without
    ever forming an intermediate that overflows `u128`. The Lean model of
    `modinverseCore` uses ordinary `ℕ` multiplication and modular
    reduction, so the proofs above don't say anything about those
    helpers. The lemmas below close that gap at the algorithm level: the
    Russian-peasant `mulMod` and the `room`-trick `addMod` both compute
    what they advertise.

    (The orthogonal claim that, under the preconditions documented in
    `src/lib.rs`, no intermediate exceeds `u128::MAX` is left to
    inspection: this Lean development does not model machine-word
    arithmetic.)
-/

/-- Lean mirror of Rust `fn add_mod_u128(a, b, m)`. The `room` trick avoids
    forming `a + b` directly, which in Rust would overflow `u128`. -/
def addMod (a b m : ℕ) : ℕ :=
  if b < m - a then a + b else b - (m - a)

lemma addMod_lt {a b m : ℕ} (ha : a < m) (hb : b < m) (_hm : 0 < m) :
    addMod a b m < m := by
  unfold addMod; split <;> omega

lemma addMod_eq {a b m : ℕ} (ha : a < m) (hb : b < m) (_hm : 0 < m) :
    addMod a b m = (a + b) % m := by
  unfold addMod
  split
  case isTrue h =>
    -- a + b < m, so (a + b) % m = a + b.
    rw [Nat.mod_eq_of_lt (by omega)]
  case isFalse h =>
    -- a + b ≥ m and a + b < 2m, so (a + b) % m = a + b - m = b - (m - a).
    have hge : m ≤ a + b := by omega
    have hlt2 : a + b - m < m := by omega
    have hrw : (a + b) % m = (a + b - m) % m := by
      conv_lhs => rw [show a + b = (a + b - m) + m from by omega]
      exact Nat.add_mod_right _ _
    rw [hrw, Nat.mod_eq_of_lt hlt2]
    omega

/-- Lean mirror of Rust `fn mul_mod_u128(a, b, m)` (Russian peasant). The
    helper loop accumulates `acc + a * b` modulo `m` by repeatedly halving
    `b` and doubling `a`; the precondition `a < m` is maintained by
    `addMod`. -/
def mulModAux (m : ℕ) : ℕ → ℕ → ℕ → ℕ
  | _, 0,     acc => acc
  | a, b + 1, acc =>
    let acc' := if (b + 1) % 2 = 1 then addMod acc a m else acc
    mulModAux m (addMod a a m) ((b + 1) / 2) acc'

/-- Lean mirror of Rust `fn mul_mod_u128(a, b, m)`. -/
def mulMod (a b m : ℕ) : ℕ :=
  if m = 0 then 0 else mulModAux m (a % m) b 0

lemma mulModAux_lt {m : ℕ} (hm : 0 < m) :
    ∀ (a b acc : ℕ), a < m → acc < m → mulModAux m a b acc < m
  | _, 0,     acc, _,  hacc => by unfold mulModAux; exact hacc
  | a, b + 1, acc, ha, hacc => by
    unfold mulModAux
    refine mulModAux_lt hm _ _ _ (addMod_lt ha ha hm) ?_
    split <;> [exact addMod_lt hacc ha hm; exact hacc]

lemma mulMod_lt {a b m : ℕ} (hm : 0 < m) : mulMod a b m < m := by
  unfold mulMod
  rw [if_neg (by omega)]
  exact mulModAux_lt hm _ _ _ (Nat.mod_lt _ hm) hm

/-- Loop invariant of `mulModAux`: it returns `(acc + a * b) % m`. -/
lemma mulModAux_eq {m : ℕ} (hm : 0 < m) :
    ∀ (a b acc : ℕ), a < m → acc < m →
      mulModAux m a b acc = (acc + a * b) % m
  | _, 0,     acc, _,  hacc => by
    unfold mulModAux
    rw [Nat.mul_zero, Nat.add_zero, Nat.mod_eq_of_lt hacc]
  | a, b + 1, acc, ha, hacc => by
    unfold mulModAux
    -- After the step, the new state is (2a mod m, (b+1)/2, acc') where
    -- acc' = addMod acc a m if (b+1) is odd, else acc.
    have ha2 : addMod a a m < m := addMod_lt ha ha hm
    set acc' : ℕ :=
      if (b + 1) % 2 = 1 then addMod acc a m else acc with hacc'
    have hacc'_lt : acc' < m := by
      rw [hacc']; split <;> [exact addMod_lt hacc ha hm; exact hacc]
    rw [mulModAux_eq hm _ _ _ ha2 hacc'_lt]
    -- Goal: (acc' + (2a mod m) * ((b+1)/2)) % m = (acc + a * (b+1)) % m.
    have h2a : addMod a a m = (2 * a) % m := by
      rw [addMod_eq ha ha hm, two_mul]
    -- Split on parity of (b+1).
    -- Both branches reduce to a `Nat.ModEq` reasoning step.
    rw [h2a]
    -- Goal: (acc' + (2*a % m) * ((b+1)/2)) % m = (acc + a * (b+1)) % m.
    -- Use ModEq congruence: (2*a % m) ≡ 2*a and acc' ≡ (whatever it equals).
    suffices h : acc' + (2 * a % m) * ((b + 1) / 2) ≡ acc + a * (b + 1) [MOD m] by
      exact h
    have h2a_mod : (2 * a) % m ≡ 2 * a [MOD m] := Nat.mod_modEq _ _
    have hmul : (2 * a % m) * ((b + 1) / 2) ≡ 2 * a * ((b + 1) / 2) [MOD m] :=
      h2a_mod.mul_right _
    by_cases hp : (b + 1) % 2 = 1
    · have hacc'_val : acc' = addMod acc a m := by rw [hacc', if_pos hp]
      have h_acc_add : addMod acc a m = (acc + a) % m := addMod_eq hacc ha hm
      have hbsplit : b + 1 = 2 * ((b + 1) / 2) + 1 := by
        have := Nat.div_add_mod (b + 1) 2; omega
      have hacc'_eq : acc' ≡ acc + a [MOD m] := by
        rw [hacc'_val, h_acc_add]; exact Nat.mod_modEq _ _
      calc acc' + (2 * a % m) * ((b + 1) / 2)
          ≡ (acc + a) + 2 * a * ((b + 1) / 2) [MOD m] := hacc'_eq.add hmul
        _ = acc + a * (2 * ((b + 1) / 2) + 1) := by ring
        _ = acc + a * (b + 1) := by rw [← hbsplit]
    · have hacc'_val : acc' = acc := by rw [hacc', if_neg hp]
      have hbsplit : b + 1 = 2 * ((b + 1) / 2) := by
        have := Nat.div_add_mod (b + 1) 2; omega
      calc acc' + (2 * a % m) * ((b + 1) / 2)
          ≡ acc + 2 * a * ((b + 1) / 2) [MOD m] := by
            rw [hacc'_val]; exact Nat.ModEq.rfl.add hmul
        _ = acc + a * (2 * ((b + 1) / 2)) := by ring
        _ = acc + a * (b + 1) := by rw [← hbsplit]

lemma mulMod_eq {a b m : ℕ} (hm : 0 < m) : mulMod a b m = (a * b) % m := by
  unfold mulMod
  rw [if_neg (by omega)]
  rw [mulModAux_eq hm _ _ _ (Nat.mod_lt _ hm) hm, Nat.zero_add,
      Nat.mod_mul_mod]

/-! ## Mechanized sanity check

    These don't add to the proof — the theorems above already cover all
    inputs. They're a cheap belt-and-braces check that the *definition*
    computes what it's supposed to. `native_decide` compiles to native code
    and runs the check at proof time.
-/

def sanityCheck (m : ℕ) (hm : 1 < m) : Bool :=
  (List.range m).all fun a =>
    match modinverseCore a m hm with
    | none   => Nat.gcd a m ≠ 1
    | some s => (a * s) % m = 1

example : sanityCheck 26 (by decide) = true := by native_decide
example : sanityCheck 97 (by decide) = true := by native_decide

end ModInverse
