/-
  # Correctness of `src/lib.rs::modinverse`, end to end

  > Generated by AI (Claude). The Lean kernel checks the proofs.

  This development is split so that *what correctness means*, *the proof that the
  algorithm achieves it*, and *the proof that the real extracted machine code
  implements the algorithm* are all maintained separately:

    ┌─ ModInverse/Model.lean ─── the algorithm (ℕ translation of the Rust;
    │                            definitions only)
    │
    ├─ ModInverse/Targets.lean ─ HUMAN-MAINTAINED - the specification: what it
    │                            means to be a correct modular inverse, as a
    │                            `structure` parameterized by the model. Read only
    │                            this file to judge whether "correct" is the right
    │                            notion.
    │
    ├─ ModInverse/Proofs.lean ── AI-MAINTAINED - the proofs that the *model* meets
    │                            the spec, ending in certificates
    │                            `isCorrect : Spec.Correct modinverse` and
    │                            `helpersCompute : Spec.HelpersCompute …`.
    │
    ├─ ../extraction/Machine.lean MACHINE-GENERATED - the Aeneas extraction of the
    │                            real Rust (`charon` + `aeneas`): `modinverse_uN`
    │                            over `Std.UN` in the `Result` monad, with overflow
    │                            and division-by-zero modelled as `fail`. Lives outside
    │                            the proof tree (imported as `Machine`) so its own
    │                            `sorry` stays out of the `no sorry in proof/` check.
    │
    └─ ModInverse/Refinement.lean AI-MAINTAINED - the proofs that the *extracted
                                 machine code* refines the model: each `modinverse_uN`
                                 never errors and value-matches `modinverse` on `.val`.

  The link between Targets and Proofs is mechanical: a certificate is a `structure`
  instance, so it fails to typecheck unless *every* target field is discharged with a
  term of exactly the declared type. Targets cannot be silently dropped or weakened,
  and adding a target forces a new proof.

  The four behavioural targets together pin down `modinverse` on every input:
  soundness (a returned witness is a real inverse), bound (`0 ≤ s < m`),
  completeness (an inverse is returned whenever one exists), and exact failure
  (`none` exactly otherwise). Two further targets state that the overflow-avoiding
  `addMod`/`mulMod` helpers compute ordinary `(a+b) % m` and `(a*b) % m`.

  Composing the `Refinement` layer (machine code refines model) with `isCorrect`
  (model meets spec) certifies the actual extracted machine code.
-/

import ModInverse.Model
import ModInverse.Targets
import ModInverse.Proofs
import Machine
import ModInverse.Refinement
