-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [modinverse]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace modinverse

/-- [core::num::{i8}::unsigned_abs]:
    Source: '/rustc/library/core/src/num/int_macros.rs', lines 2486:8-2486:53
    Name pattern: [core::num::{i8}::unsigned_abs]
    Visibility: public -/
@[rust_fun "core::num::{i8}::unsigned_abs"]
axiom core.num.I8.unsigned_abs : Std.I8 → Result Std.U8

/-- [core::num::{i16}::unsigned_abs]:
    Source: '/rustc/library/core/src/num/int_macros.rs', lines 2486:8-2486:53
    Name pattern: [core::num::{i16}::unsigned_abs]
    Visibility: public -/
@[rust_fun "core::num::{i16}::unsigned_abs"]
axiom core.num.I16.unsigned_abs : Std.I16 → Result Std.U16

/-- [core::num::{i32}::unsigned_abs]:
    Source: '/rustc/library/core/src/num/int_macros.rs', lines 2486:8-2486:53
    Name pattern: [core::num::{i32}::unsigned_abs]
    Visibility: public -/
@[rust_fun "core::num::{i32}::unsigned_abs"]
axiom core.num.I32.unsigned_abs : Std.I32 → Result Std.U32

/-- [core::num::{i64}::unsigned_abs]:
    Source: '/rustc/library/core/src/num/int_macros.rs', lines 2486:8-2486:53
    Name pattern: [core::num::{i64}::unsigned_abs]
    Visibility: public -/
@[rust_fun "core::num::{i64}::unsigned_abs"]
axiom core.num.I64.unsigned_abs : Std.I64 → Result Std.U64

/-- [core::num::{i128}::unsigned_abs]:
    Source: '/rustc/library/core/src/num/int_macros.rs', lines 2486:8-2486:53
    Name pattern: [core::num::{i128}::unsigned_abs]
    Visibility: public -/
@[rust_fun "core::num::{i128}::unsigned_abs"]
axiom core.num.I128.unsigned_abs : Std.I128 → Result Std.U128

/-- Trait declaration: [core::ops::arith::Add]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 76:0-76:31
    Name pattern: [core::ops::arith::Add]
    Visibility: public -/
@[rust_trait "core::ops::arith::Add"]
structure core.ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  add : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Sub]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 188:0-188:31
    Name pattern: [core::ops::arith::Sub]
    Visibility: public -/
@[rust_trait "core::ops::arith::Sub"]
structure core.ops.arith.Sub (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  sub : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Mul]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 322:0-322:31
    Name pattern: [core::ops::arith::Mul]
    Visibility: public -/
@[rust_trait "core::ops::arith::Mul"]
structure core.ops.arith.Mul (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  mul : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Div]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 460:0-460:31
    Name pattern: [core::ops::arith::Div]
    Visibility: public -/
@[rust_trait "core::ops::arith::Div"]
structure core.ops.arith.Div (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  div : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Rem]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 569:0-569:31
    Name pattern: [core::ops::arith::Rem]
    Visibility: public -/
@[rust_trait "core::ops::arith::Rem"]
structure core.ops.arith.Rem (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  rem : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Neg]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 690:0-690:19
    Name pattern: [core::ops::arith::Neg]
    Visibility: public -/
@[rust_trait "core::ops::arith::Neg"]
structure core.ops.arith.Neg (Self : Type) (Self_Output : Type) where
  neg : Self → Result Self_Output

/-- [core::option::{core::option::Option<T>}::map]:
    Source: '/rustc/library/core/src/option.rs', lines 1157:4-1159:53
    Name pattern: [core::option::{core::option::Option<@T>}::map]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::map"]
axiom core.option.Option.map
  {T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) :
  Option T → F → Result (Option U)

/-- Trait declaration: [num_traits::NumOps]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-traits-0.2.19/src/lib.rs', lines 101:0-106:31
    Name pattern: [num_traits::NumOps]
    Visibility: public -/
@[rust_trait "num_traits::NumOps"
  (parentClauses := ["coreopsarithAddInst", "coreopsarithSubInst", "coreopsarithMulInst", "coreopsarithDivInst", "coreopsarithRemInst"])]
structure num_traits.NumOps (Self : Type) (Rhs : Type) (Output : Type) where
  coreopsarithAddInst : core.ops.arith.Add Self Rhs Output
  coreopsarithSubInst : core.ops.arith.Sub Self Rhs Output
  coreopsarithMulInst : core.ops.arith.Mul Self Rhs Output
  coreopsarithDivInst : core.ops.arith.Div Self Rhs Output
  coreopsarithRemInst : core.ops.arith.Rem Self Rhs Output

/-- Trait declaration: [num_traits::identities::One]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-traits-0.2.19/src/identities.rs', lines 106:0-106:47
    Name pattern: [num_traits::identities::One]
    Visibility: public -/
@[rust_trait "num_traits::identities::One"
  (parentClauses := ["coreopsarithMulInst"])]
structure num_traits.identities.One (Self : Type) where
  coreopsarithMulInst : core.ops.arith.Mul Self Self Self
  one : Result Self

/-- Trait declaration: [num_traits::identities::Zero]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-traits-0.2.19/src/identities.rs', lines 12:0-12:48
    Name pattern: [num_traits::identities::Zero]
    Visibility: public -/
@[rust_trait "num_traits::identities::Zero"
  (parentClauses := ["coreopsarithAddInst"])]
structure num_traits.identities.Zero (Self : Type) where
  coreopsarithAddInst : core.ops.arith.Add Self Self Self
  zero : Result Self
  is_zero : Self → Result Bool

/-- Trait declaration: [num_traits::Num]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-traits-0.2.19/src/lib.rs', lines 67:0-67:46
    Name pattern: [num_traits::Num]
    Visibility: public -/
@[rust_trait "num_traits::Num"
  (parentClauses := ["corecmpPartialEqInst", "identitiesZeroInst", "identitiesOneInst", "NumOpsInst"])]
structure num_traits.Num (Self : Type) (Self_FromStrRadixErr : Type) where
  corecmpPartialEqInst : core.cmp.PartialEq Self Self
  identitiesZeroInst : num_traits.identities.Zero Self
  identitiesOneInst : num_traits.identities.One Self
  NumOpsInst : num_traits.NumOps Self Self Self
  from_str_radix : Str → Std.U32 → Result (core.result.Result Self
    Self_FromStrRadixErr)

/-- Trait declaration: [num_integer::Integer]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-integer-0.1.46/src/lib.rs', lines 33:0-33:54
    Name pattern: [num_integer::Integer]
    Visibility: public -/
@[rust_trait "num_integer::Integer"
  (parentClauses := ["num_traitsNumInst", "corecmpPartialOrdInst", "corecmpOrdInst", "corecmpEqInst"])]
structure num_integer.Integer (Self : Type) (Self_Clause0_FromStrRadixErr :
  Type) where
  num_traitsNumInst : num_traits.Num Self Self_Clause0_FromStrRadixErr
  corecmpPartialOrdInst : core.cmp.PartialOrd Self Self
  corecmpOrdInst : core.cmp.Ord Self
  corecmpEqInst : core.cmp.Eq Self
  div_floor : Self → Self → Result Self
  mod_floor : Self → Self → Result Self
  gcd : Self → Self → Result Self
  lcm : Self → Self → Result Self
  is_multiple_of : Self → Self → Result Bool
  is_even : Self → Result Bool
  is_odd : Self → Result Bool
  div_rem : Self → Self → Result (Self × Self)

/-- Trait declaration: [num_traits::sign::Signed]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-traits-0.2.19/src/sign.rs', lines 8:0-8:50
    Name pattern: [num_traits::sign::Signed]
    Visibility: public -/
@[rust_trait "num_traits::sign::Signed"
  (parentClauses := ["NumInst", "coreopsarithNegInst"])]
structure num_traits.sign.Signed (Self : Type) (Self_Clause0_FromStrRadixErr :
  Type) where
  NumInst : num_traits.Num Self Self_Clause0_FromStrRadixErr
  coreopsarithNegInst : core.ops.arith.Neg Self Self
  abs : Self → Result Self
  abs_sub : Self → Self → Result Self
  signum : Self → Result Self
  is_positive : Self → Result Bool
  is_negative : Self → Result Bool

/-- [modinverse::egcd]:
    Source: 'src/lib.rs', lines 58:0-72:1
    Visibility: public -/
def egcd
  {T : Type} {Clause1_Clause0_FromStrRadixErr : Type}
  {Clause2_Clause0_FromStrRadixErr : Type} (corecloneCloneInst :
  core.clone.Clone T) (num_integerIntegerInst : num_integer.Integer T
  Clause1_Clause0_FromStrRadixErr) (num_traitssignSignedInst :
  num_traits.sign.Signed T Clause2_Clause0_FromStrRadixErr) (a : T) (b : T) :
  Result (T × T × T)
  := do
  sorry

/-- Trait declaration: [modinverse::ModInverse]
    Source: 'src/lib.rs', lines 177:0-179:1
    Visibility: public -/
structure ModInverse (Self : Type) where
  modinverse : Self → Self → Result (Option Self)

/-- [modinverse::modinverse]:
    Source: 'src/lib.rs', lines 189:0-191:1
    Visibility: public -/
def modinverse
  {T : Type} (ModInverseInst : ModInverse T) (a : T) (m : T) :
  Result (Option T)
  := do
  ModInverseInst.modinverse a m

/-- [modinverse::mul_mod_u8]:
    Source: 'src/lib.rs', lines 204:0-206:1 -/
def mul_mod_u8 (a : Std.U8) (b : Std.U8) (m : Std.U8) : Result Std.U8 := do
  let i ← lift (UScalar.cast .U16 a)
  let i1 ← lift (UScalar.cast .U16 b)
  let i2 ← i * i1
  let i3 ← lift (UScalar.cast .U16 m)
  let i4 ← i2 % i3
  ok (UScalar.cast .U8 i4)

/-- [modinverse::mul_mod_u16]:
    Source: 'src/lib.rs', lines 207:0-209:1 -/
def mul_mod_u16
  (a : Std.U16) (b : Std.U16) (m : Std.U16) : Result Std.U16 := do
  let i ← lift (UScalar.cast .U32 a)
  let i1 ← lift (UScalar.cast .U32 b)
  let i2 ← i * i1
  let i3 ← lift (UScalar.cast .U32 m)
  let i4 ← i2 % i3
  ok (UScalar.cast .U16 i4)

/-- [modinverse::mul_mod_u32]:
    Source: 'src/lib.rs', lines 210:0-212:1 -/
def mul_mod_u32
  (a : Std.U32) (b : Std.U32) (m : Std.U32) : Result Std.U32 := do
  let i ← lift (UScalar.cast .U64 a)
  let i1 ← lift (UScalar.cast .U64 b)
  let i2 ← i * i1
  let i3 ← lift (UScalar.cast .U64 m)
  let i4 ← i2 % i3
  ok (UScalar.cast .U32 i4)

/-- [modinverse::mul_mod_u64]:
    Source: 'src/lib.rs', lines 213:0-215:1 -/
def mul_mod_u64
  (a : Std.U64) (b : Std.U64) (m : Std.U64) : Result Std.U64 := do
  let i ← lift (UScalar.cast .U128 a)
  let i1 ← lift (UScalar.cast .U128 b)
  let i2 ← i * i1
  let i3 ← lift (UScalar.cast .U128 m)
  let i4 ← i2 % i3
  ok (UScalar.cast .U64 i4)

/-- [modinverse::modinverse_u8]: loop 0:
    Source: 'src/lib.rs', lines 231:12-238:13 -/
@[rust_loop]
def modinverse_u8_loop
  (m : Std.U8) (r : Std.U8) (r_next : Std.U8) (s : Std.U8) (s_next : Std.U8) :
  Result (Std.U8 × Std.U8)
  := do
  if r_next != 0#u8
  then
    let q ← r / r_next
    let rem ← r % r_next
    let qs ← mul_mod_u8 q s_next m
    if s >= qs
    then let s_new ← s - qs
         modinverse_u8_loop m r_next rem s_next s_new
    else
      let i ← m - qs
      let s_new ← i + s
      modinverse_u8_loop m r_next rem s_next s_new
  else ok (r, s)
partial_fixpoint

/-- [modinverse::modinverse_u8]:
    Source: 'src/lib.rs', lines 222:8-244:9 -/
def modinverse_u8 (a : Std.U8) (m : Std.U8) : Result (Option Std.U8) := do
  if m = 0#u8
  then ok none
  else
    if m = 1#u8
    then ok (some 0#u8)
    else
      let r_next ← a % m
      let (r, s) ← modinverse_u8_loop m m r_next 0#u8 1#u8
      if r = 1#u8
      then ok (some s)
      else ok none

/-- [modinverse::modinverse_u16]: loop 0:
    Source: 'src/lib.rs', lines 231:12-238:13 -/
@[rust_loop]
def modinverse_u16_loop
  (m : Std.U16) (r : Std.U16) (r_next : Std.U16) (s : Std.U16)
  (s_next : Std.U16) :
  Result (Std.U16 × Std.U16)
  := do
  if r_next != 0#u16
  then
    let q ← r / r_next
    let rem ← r % r_next
    let qs ← mul_mod_u16 q s_next m
    if s >= qs
    then let s_new ← s - qs
         modinverse_u16_loop m r_next rem s_next s_new
    else
      let i ← m - qs
      let s_new ← i + s
      modinverse_u16_loop m r_next rem s_next s_new
  else ok (r, s)
partial_fixpoint

/-- [modinverse::modinverse_u16]:
    Source: 'src/lib.rs', lines 222:8-244:9 -/
def modinverse_u16 (a : Std.U16) (m : Std.U16) : Result (Option Std.U16) := do
  if m = 0#u16
  then ok none
  else
    if m = 1#u16
    then ok (some 0#u16)
    else
      let r_next ← a % m
      let (r, s) ← modinverse_u16_loop m m r_next 0#u16 1#u16
      if r = 1#u16
      then ok (some s)
      else ok none

/-- [modinverse::modinverse_u32]: loop 0:
    Source: 'src/lib.rs', lines 231:12-238:13 -/
@[rust_loop]
def modinverse_u32_loop
  (m : Std.U32) (r : Std.U32) (r_next : Std.U32) (s : Std.U32)
  (s_next : Std.U32) :
  Result (Std.U32 × Std.U32)
  := do
  if r_next != 0#u32
  then
    let q ← r / r_next
    let rem ← r % r_next
    let qs ← mul_mod_u32 q s_next m
    if s >= qs
    then let s_new ← s - qs
         modinverse_u32_loop m r_next rem s_next s_new
    else
      let i ← m - qs
      let s_new ← i + s
      modinverse_u32_loop m r_next rem s_next s_new
  else ok (r, s)
partial_fixpoint

/-- [modinverse::modinverse_u32]:
    Source: 'src/lib.rs', lines 222:8-244:9 -/
def modinverse_u32 (a : Std.U32) (m : Std.U32) : Result (Option Std.U32) := do
  if m = 0#u32
  then ok none
  else
    if m = 1#u32
    then ok (some 0#u32)
    else
      let r_next ← a % m
      let (r, s) ← modinverse_u32_loop m m r_next 0#u32 1#u32
      if r = 1#u32
      then ok (some s)
      else ok none

/-- [modinverse::modinverse_u64]: loop 0:
    Source: 'src/lib.rs', lines 231:12-238:13 -/
@[rust_loop]
def modinverse_u64_loop
  (m : Std.U64) (r : Std.U64) (r_next : Std.U64) (s : Std.U64)
  (s_next : Std.U64) :
  Result (Std.U64 × Std.U64)
  := do
  if r_next != 0#u64
  then
    let q ← r / r_next
    let rem ← r % r_next
    let qs ← mul_mod_u64 q s_next m
    if s >= qs
    then let s_new ← s - qs
         modinverse_u64_loop m r_next rem s_next s_new
    else
      let i ← m - qs
      let s_new ← i + s
      modinverse_u64_loop m r_next rem s_next s_new
  else ok (r, s)
partial_fixpoint

/-- [modinverse::modinverse_u64]:
    Source: 'src/lib.rs', lines 222:8-244:9 -/
def modinverse_u64 (a : Std.U64) (m : Std.U64) : Result (Option Std.U64) := do
  if m = 0#u64
  then ok none
  else
    if m = 1#u64
    then ok (some 0#u64)
    else
      let r_next ← a % m
      let (r, s) ← modinverse_u64_loop m m r_next 0#u64 1#u64
      if r = 1#u64
      then ok (some s)
      else ok none

/-- [modinverse::add_mod_u128]:
    Source: 'src/lib.rs', lines 314:0-321:1 -/
def add_mod_u128
  (a : Std.U128) (b : Std.U128) (m : Std.U128) : Result Std.U128 := do
  let room ← m - a
  if b < room
  then a + b
  else b - room

/-- [modinverse::mul_mod_u128]: loop 0:
    Source: 'src/lib.rs', lines 303:4-309:5 -/
@[rust_loop]
def mul_mod_u128_loop
  (a : Std.U128) (b : Std.U128) (m : Std.U128) (result : Std.U128) :
  Result Std.U128
  := do
  if b > 0#u128
  then
    let i ← lift (b &&& 1#u128)
    let result1 ← if i = 1#u128
                    then add_mod_u128 result a m
                    else ok result
    let a1 ← add_mod_u128 a a m
    let b1 ← b >>> 1#i32
    mul_mod_u128_loop a1 b1 m result1
  else ok result
partial_fixpoint

/-- [modinverse::mul_mod_u128]:
    Source: 'src/lib.rs', lines 300:0-311:1 -/
def mul_mod_u128
  (a : Std.U128) (b : Std.U128) (m : Std.U128) : Result Std.U128 := do
  let a1 ← a % m
  mul_mod_u128_loop a1 b m 0#u128

/-- [modinverse::modinverse_u128]: loop 0:
    Source: 'src/lib.rs', lines 231:12-238:13 -/
@[rust_loop]
def modinverse_u128_loop
  (m : Std.U128) (r : Std.U128) (r_next : Std.U128) (s : Std.U128)
  (s_next : Std.U128) :
  Result (Std.U128 × Std.U128)
  := do
  if r_next != 0#u128
  then
    let q ← r / r_next
    let rem ← r % r_next
    let qs ← mul_mod_u128 q s_next m
    if s >= qs
    then let s_new ← s - qs
         modinverse_u128_loop m r_next rem s_next s_new
    else
      let i ← m - qs
      let s_new ← i + s
      modinverse_u128_loop m r_next rem s_next s_new
  else ok (r, s)
partial_fixpoint

/-- [modinverse::modinverse_u128]:
    Source: 'src/lib.rs', lines 222:8-244:9 -/
def modinverse_u128
  (a : Std.U128) (m : Std.U128) : Result (Option Std.U128) := do
  if m = 0#u128
  then ok none
  else
    if m = 1#u128
    then ok (some 0#u128)
    else
      let r_next ← a % m
      let (r, s) ← modinverse_u128_loop m m r_next 0#u128 1#u128
      if r = 1#u128
      then ok (some s)
      else ok none

/-- [modinverse::{impl modinverse::ModInverse for u8}::modinverse]:
    Source: 'src/lib.rs', lines 258:12-260:13
    Visibility: public -/
def U8.Insts.ModinverseModInverse.modinverse
  (self : Std.U8) (m : Std.U8) : Result (Option Std.U8) := do
  modinverse_u8 self m

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for u8}]
    Source: 'src/lib.rs', lines 257:8-261:9 -/
@[reducible]
def U8.Insts.ModinverseModInverse : ModInverse Std.U8 := {
  modinverse := U8.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for u16}::modinverse]:
    Source: 'src/lib.rs', lines 258:12-260:13
    Visibility: public -/
def U16.Insts.ModinverseModInverse.modinverse
  (self : Std.U16) (m : Std.U16) : Result (Option Std.U16) := do
  modinverse_u16 self m

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for u16}]
    Source: 'src/lib.rs', lines 257:8-261:9 -/
@[reducible]
def U16.Insts.ModinverseModInverse : ModInverse Std.U16 := {
  modinverse := U16.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for u32}::modinverse]:
    Source: 'src/lib.rs', lines 258:12-260:13
    Visibility: public -/
def U32.Insts.ModinverseModInverse.modinverse
  (self : Std.U32) (m : Std.U32) : Result (Option Std.U32) := do
  modinverse_u32 self m

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for u32}]
    Source: 'src/lib.rs', lines 257:8-261:9 -/
@[reducible]
def U32.Insts.ModinverseModInverse : ModInverse Std.U32 := {
  modinverse := U32.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for u64}::modinverse]:
    Source: 'src/lib.rs', lines 258:12-260:13
    Visibility: public -/
def U64.Insts.ModinverseModInverse.modinverse
  (self : Std.U64) (m : Std.U64) : Result (Option Std.U64) := do
  modinverse_u64 self m

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for u64}]
    Source: 'src/lib.rs', lines 257:8-261:9 -/
@[reducible]
def U64.Insts.ModinverseModInverse : ModInverse Std.U64 := {
  modinverse := U64.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for u128}::modinverse]:
    Source: 'src/lib.rs', lines 258:12-260:13
    Visibility: public -/
def U128.Insts.ModinverseModInverse.modinverse
  (self : Std.U128) (m : Std.U128) : Result (Option Std.U128) := do
  modinverse_u128 self m

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for u128}]
    Source: 'src/lib.rs', lines 257:8-261:9 -/
@[reducible]
def U128.Insts.ModinverseModInverse : ModInverse Std.U128 := {
  modinverse := U128.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for i8}::modinverse::closure]
    Source: 'src/lib.rs', lines 278:28-286:46 -/
@[reducible]
def ModInverseI8.modinverse.closure := Unit

/-- [modinverse::{impl modinverse::ModInverse for i8}::modinverse::{impl core::ops::function::FnOnce<(u8,), i8> for modinverse::{impl modinverse::ModInverse for i8}::modinverse::closure}::call_once]:
    Source: 'src/lib.rs', lines 278:28-286:46 -/
def
  ModInverseI8.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU8I8.call_once
  (c : ModInverseI8.modinverse.closure) (tupled_args : Std.U8) :
  Result Std.I8
  := do
  ok (UScalar.hcast .I8 tupled_args)

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for i8}::modinverse::{impl core::ops::function::FnOnce<(u8,), i8> for modinverse::{impl modinverse::ModInverse for i8}::modinverse::closure}]
    Source: 'src/lib.rs', lines 278:28-286:46 -/
@[reducible]
def ModInverseI8.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU8I8 :
  core.ops.function.FnOnce ModInverseI8.modinverse.closure Std.U8 Std.I8 := {
  call_once :=
    ModInverseI8.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU8I8.call_once
}

/-- [modinverse::{impl modinverse::ModInverse for i8}::modinverse]:
    Source: 'src/lib.rs', lines 279:12-287:13
    Visibility: public -/
def I8.Insts.ModinverseModInverse.modinverse
  (self : Std.I8) (m : Std.I8) : Result (Option Std.I8) := do
  if m = 0#i8
  then ok none
  else
    let m_abs ← core.num.I8.unsigned_abs m
    let i ← core.num.I8.unsigned_abs self
    let a_abs ← i % m_abs
    let a_u ←
      if self < 0#i8
      then if a_abs != 0#u8
           then m_abs - a_abs
           else ok a_abs
      else ok a_abs
    let o ← modinverse_u8 a_u m_abs
    core.option.Option.map
      ModInverseI8.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU8I8 o ()

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for i8}]
    Source: 'src/lib.rs', lines 278:8-288:9 -/
@[reducible]
def I8.Insts.ModinverseModInverse : ModInverse Std.I8 := {
  modinverse := I8.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for i16}::modinverse::closure]
    Source: 'src/lib.rs', lines 278:28-286:46 -/
@[reducible]
def ModInverseI16.modinverse.closure := Unit

/-- [modinverse::{impl modinverse::ModInverse for i16}::modinverse::{impl core::ops::function::FnOnce<(u16,), i16> for modinverse::{impl modinverse::ModInverse for i16}::modinverse::closure}::call_once]:
    Source: 'src/lib.rs', lines 278:28-286:46 -/
def
  ModInverseI16.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU16I16.call_once
  (c : ModInverseI16.modinverse.closure) (tupled_args : Std.U16) :
  Result Std.I16
  := do
  ok (UScalar.hcast .I16 tupled_args)

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for i16}::modinverse::{impl core::ops::function::FnOnce<(u16,), i16> for modinverse::{impl modinverse::ModInverse for i16}::modinverse::closure}]
    Source: 'src/lib.rs', lines 278:28-286:46 -/
@[reducible]
def ModInverseI16.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU16I16 :
  core.ops.function.FnOnce ModInverseI16.modinverse.closure Std.U16 Std.I16
  := {
  call_once :=
    ModInverseI16.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU16I16.call_once
}

/-- [modinverse::{impl modinverse::ModInverse for i16}::modinverse]:
    Source: 'src/lib.rs', lines 279:12-287:13
    Visibility: public -/
def I16.Insts.ModinverseModInverse.modinverse
  (self : Std.I16) (m : Std.I16) : Result (Option Std.I16) := do
  if m = 0#i16
  then ok none
  else
    let m_abs ← core.num.I16.unsigned_abs m
    let i ← core.num.I16.unsigned_abs self
    let a_abs ← i % m_abs
    let a_u ←
      if self < 0#i16
      then if a_abs != 0#u16
           then m_abs - a_abs
           else ok a_abs
      else ok a_abs
    let o ← modinverse_u16 a_u m_abs
    core.option.Option.map
      ModInverseI16.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU16I16 o
      ()

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for i16}]
    Source: 'src/lib.rs', lines 278:8-288:9 -/
@[reducible]
def I16.Insts.ModinverseModInverse : ModInverse Std.I16 := {
  modinverse := I16.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for i32}::modinverse::closure]
    Source: 'src/lib.rs', lines 278:28-286:46 -/
@[reducible]
def ModInverseI32.modinverse.closure := Unit

/-- [modinverse::{impl modinverse::ModInverse for i32}::modinverse::{impl core::ops::function::FnOnce<(u32,), i32> for modinverse::{impl modinverse::ModInverse for i32}::modinverse::closure}::call_once]:
    Source: 'src/lib.rs', lines 278:28-286:46 -/
def
  ModInverseI32.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU32I32.call_once
  (c : ModInverseI32.modinverse.closure) (tupled_args : Std.U32) :
  Result Std.I32
  := do
  ok (UScalar.hcast .I32 tupled_args)

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for i32}::modinverse::{impl core::ops::function::FnOnce<(u32,), i32> for modinverse::{impl modinverse::ModInverse for i32}::modinverse::closure}]
    Source: 'src/lib.rs', lines 278:28-286:46 -/
@[reducible]
def ModInverseI32.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU32I32 :
  core.ops.function.FnOnce ModInverseI32.modinverse.closure Std.U32 Std.I32
  := {
  call_once :=
    ModInverseI32.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU32I32.call_once
}

/-- [modinverse::{impl modinverse::ModInverse for i32}::modinverse]:
    Source: 'src/lib.rs', lines 279:12-287:13
    Visibility: public -/
def I32.Insts.ModinverseModInverse.modinverse
  (self : Std.I32) (m : Std.I32) : Result (Option Std.I32) := do
  if m = 0#i32
  then ok none
  else
    let m_abs ← core.num.I32.unsigned_abs m
    let i ← core.num.I32.unsigned_abs self
    let a_abs ← i % m_abs
    let a_u ←
      if self < 0#i32
      then if a_abs != 0#u32
           then m_abs - a_abs
           else ok a_abs
      else ok a_abs
    let o ← modinverse_u32 a_u m_abs
    core.option.Option.map
      ModInverseI32.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU32I32 o
      ()

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for i32}]
    Source: 'src/lib.rs', lines 278:8-288:9 -/
@[reducible]
def I32.Insts.ModinverseModInverse : ModInverse Std.I32 := {
  modinverse := I32.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for i64}::modinverse::closure]
    Source: 'src/lib.rs', lines 278:28-286:46 -/
@[reducible]
def ModInverseI64.modinverse.closure := Unit

/-- [modinverse::{impl modinverse::ModInverse for i64}::modinverse::{impl core::ops::function::FnOnce<(u64,), i64> for modinverse::{impl modinverse::ModInverse for i64}::modinverse::closure}::call_once]:
    Source: 'src/lib.rs', lines 278:28-286:46 -/
def
  ModInverseI64.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU64I64.call_once
  (c : ModInverseI64.modinverse.closure) (tupled_args : Std.U64) :
  Result Std.I64
  := do
  ok (UScalar.hcast .I64 tupled_args)

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for i64}::modinverse::{impl core::ops::function::FnOnce<(u64,), i64> for modinverse::{impl modinverse::ModInverse for i64}::modinverse::closure}]
    Source: 'src/lib.rs', lines 278:28-286:46 -/
@[reducible]
def ModInverseI64.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU64I64 :
  core.ops.function.FnOnce ModInverseI64.modinverse.closure Std.U64 Std.I64
  := {
  call_once :=
    ModInverseI64.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU64I64.call_once
}

/-- [modinverse::{impl modinverse::ModInverse for i64}::modinverse]:
    Source: 'src/lib.rs', lines 279:12-287:13
    Visibility: public -/
def I64.Insts.ModinverseModInverse.modinverse
  (self : Std.I64) (m : Std.I64) : Result (Option Std.I64) := do
  if m = 0#i64
  then ok none
  else
    let m_abs ← core.num.I64.unsigned_abs m
    let i ← core.num.I64.unsigned_abs self
    let a_abs ← i % m_abs
    let a_u ←
      if self < 0#i64
      then if a_abs != 0#u64
           then m_abs - a_abs
           else ok a_abs
      else ok a_abs
    let o ← modinverse_u64 a_u m_abs
    core.option.Option.map
      ModInverseI64.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU64I64 o
      ()

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for i64}]
    Source: 'src/lib.rs', lines 278:8-288:9 -/
@[reducible]
def I64.Insts.ModinverseModInverse : ModInverse Std.I64 := {
  modinverse := I64.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for i128}::modinverse::closure]
    Source: 'src/lib.rs', lines 278:28-286:46 -/
@[reducible]
def ModInverseI128.modinverse.closure := Unit

/-- [modinverse::{impl modinverse::ModInverse for i128}::modinverse::{impl core::ops::function::FnOnce<(u128,), i128> for modinverse::{impl modinverse::ModInverse for i128}::modinverse::closure}::call_once]:
    Source: 'src/lib.rs', lines 278:28-286:46 -/
def
  ModInverseI128.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU128I128.call_once
  (c : ModInverseI128.modinverse.closure) (tupled_args : Std.U128) :
  Result Std.I128
  := do
  ok (UScalar.hcast .I128 tupled_args)

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for i128}::modinverse::{impl core::ops::function::FnOnce<(u128,), i128> for modinverse::{impl modinverse::ModInverse for i128}::modinverse::closure}]
    Source: 'src/lib.rs', lines 278:28-286:46 -/
@[reducible]
def ModInverseI128.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU128I128
  : core.ops.function.FnOnce ModInverseI128.modinverse.closure Std.U128
  Std.I128 := {
  call_once :=
    ModInverseI128.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU128I128.call_once
}

/-- [modinverse::{impl modinverse::ModInverse for i128}::modinverse]:
    Source: 'src/lib.rs', lines 279:12-287:13
    Visibility: public -/
def I128.Insts.ModinverseModInverse.modinverse
  (self : Std.I128) (m : Std.I128) : Result (Option Std.I128) := do
  if m = 0#i128
  then ok none
  else
    let m_abs ← core.num.I128.unsigned_abs m
    let i ← core.num.I128.unsigned_abs self
    let a_abs ← i % m_abs
    let a_u ←
      if self < 0#i128
      then if a_abs != 0#u128
           then m_abs - a_abs
           else ok a_abs
      else ok a_abs
    let o ← modinverse_u128 a_u m_abs
    core.option.Option.map
      ModInverseI128.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU128I128
      o ()

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for i128}]
    Source: 'src/lib.rs', lines 278:8-288:9 -/
@[reducible]
def I128.Insts.ModinverseModInverse : ModInverse Std.I128 := {
  modinverse := I128.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for usize}::modinverse::closure]
    Source: 'src/lib.rs', lines 352:47-352:61 -/
@[reducible]
def ModInverseUsize.modinverse.closure := Unit

/-- [modinverse::{impl modinverse::ModInverse for usize}::modinverse::{impl core::ops::function::FnOnce<(u64,), usize> for modinverse::{impl modinverse::ModInverse for usize}::modinverse::closure}::call_once]:
    Source: 'src/lib.rs', lines 352:47-352:61 -/
def
  ModInverseUsize.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU64Usize.call_once
  (c : ModInverseUsize.modinverse.closure) (tupled_args : Std.U64) :
  Result Std.Usize
  := do
  ok (UScalar.cast .Usize tupled_args)

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for usize}::modinverse::{impl core::ops::function::FnOnce<(u64,), usize> for modinverse::{impl modinverse::ModInverse for usize}::modinverse::closure}]
    Source: 'src/lib.rs', lines 352:47-352:61 -/
@[reducible]
def ModInverseUsize.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU64Usize
  : core.ops.function.FnOnce ModInverseUsize.modinverse.closure Std.U64
  Std.Usize := {
  call_once :=
    ModInverseUsize.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU64Usize.call_once
}

/-- [modinverse::{impl modinverse::ModInverse for usize}::modinverse]:
    Source: 'src/lib.rs', lines 351:4-353:5
    Visibility: public -/
def Usize.Insts.ModinverseModInverse.modinverse
  (self : Std.Usize) (m : Std.Usize) : Result (Option Std.Usize) := do
  let i ← lift (UScalar.cast .U64 self)
  let i1 ← lift (UScalar.cast .U64 m)
  let o ← U64.Insts.ModinverseModInverse.modinverse i i1
  core.option.Option.map
    ModInverseUsize.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleU64Usize
    o ()

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for usize}]
    Source: 'src/lib.rs', lines 350:0-354:1 -/
@[reducible]
def Usize.Insts.ModinverseModInverse : ModInverse Std.Usize := {
  modinverse := Usize.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for isize}::modinverse::closure]
    Source: 'src/lib.rs', lines 371:47-371:61 -/
@[reducible]
def ModInverseIsize.modinverse.closure := Unit

/-- [modinverse::{impl modinverse::ModInverse for isize}::modinverse::{impl core::ops::function::FnOnce<(i64,), isize> for modinverse::{impl modinverse::ModInverse for isize}::modinverse::closure}::call_once]:
    Source: 'src/lib.rs', lines 371:47-371:61 -/
def
  ModInverseIsize.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleI64Isize.call_once
  (c : ModInverseIsize.modinverse.closure) (tupled_args : Std.I64) :
  Result Std.Isize
  := do
  ok (IScalar.cast .Isize tupled_args)

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for isize}::modinverse::{impl core::ops::function::FnOnce<(i64,), isize> for modinverse::{impl modinverse::ModInverse for isize}::modinverse::closure}]
    Source: 'src/lib.rs', lines 371:47-371:61 -/
@[reducible]
def ModInverseIsize.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleI64Isize
  : core.ops.function.FnOnce ModInverseIsize.modinverse.closure Std.I64
  Std.Isize := {
  call_once :=
    ModInverseIsize.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleI64Isize.call_once
}

/-- [modinverse::{impl modinverse::ModInverse for isize}::modinverse]:
    Source: 'src/lib.rs', lines 370:4-372:5
    Visibility: public -/
def Isize.Insts.ModinverseModInverse.modinverse
  (self : Std.Isize) (m : Std.Isize) : Result (Option Std.Isize) := do
  let i ← lift (IScalar.cast .I64 self)
  let i1 ← lift (IScalar.cast .I64 m)
  let o ← I64.Insts.ModinverseModInverse.modinverse i i1
  core.option.Option.map
    ModInverseIsize.modinverse.closure.Insts.CoreOpsFunctionFnOnceTupleI64Isize
    o ()

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for isize}]
    Source: 'src/lib.rs', lines 369:0-373:1 -/
@[reducible]
def Isize.Insts.ModinverseModInverse : ModInverse Std.Isize := {
  modinverse := Isize.Insts.ModinverseModInverse.modinverse
}

end modinverse
