-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [modinverse]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace modinverse

/-- Trait declaration: [core::ops::arith::Add]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 76:0-76:31
    Name pattern: [core::ops::arith::Add]
    Visibility: public -/
@[rust_trait "core::ops::arith::Add"]
structure core.ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  add : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Sub]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 188:0-188:31
    Name pattern: [core::ops::arith::Sub]
    Visibility: public -/
@[rust_trait "core::ops::arith::Sub"]
structure core.ops.arith.Sub (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  sub : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Mul]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 322:0-322:31
    Name pattern: [core::ops::arith::Mul]
    Visibility: public -/
@[rust_trait "core::ops::arith::Mul"]
structure core.ops.arith.Mul (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  mul : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Div]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 460:0-460:31
    Name pattern: [core::ops::arith::Div]
    Visibility: public -/
@[rust_trait "core::ops::arith::Div"]
structure core.ops.arith.Div (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  div : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Rem]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 569:0-569:31
    Name pattern: [core::ops::arith::Rem]
    Visibility: public -/
@[rust_trait "core::ops::arith::Rem"]
structure core.ops.arith.Rem (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  rem : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Neg]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 690:0-690:19
    Name pattern: [core::ops::arith::Neg]
    Visibility: public -/
@[rust_trait "core::ops::arith::Neg"]
structure core.ops.arith.Neg (Self : Type) (Self_Output : Type) where
  neg : Self → Result Self_Output

/-- Trait declaration: [num_traits::NumOps]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-traits-0.2.19/src/lib.rs', lines 101:0-106:31
    Name pattern: [num_traits::NumOps]
    Visibility: public -/
@[rust_trait "num_traits::NumOps"
  (parentClauses := ["coreopsarithAddInst", "coreopsarithSubInst", "coreopsarithMulInst", "coreopsarithDivInst", "coreopsarithRemInst"])]
structure num_traits.NumOps (Self : Type) (Rhs : Type) (Output : Type) where
  coreopsarithAddInst : core.ops.arith.Add Self Rhs Output
  coreopsarithSubInst : core.ops.arith.Sub Self Rhs Output
  coreopsarithMulInst : core.ops.arith.Mul Self Rhs Output
  coreopsarithDivInst : core.ops.arith.Div Self Rhs Output
  coreopsarithRemInst : core.ops.arith.Rem Self Rhs Output

/-- Trait declaration: [num_traits::identities::One]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-traits-0.2.19/src/identities.rs', lines 106:0-106:47
    Name pattern: [num_traits::identities::One]
    Visibility: public -/
@[rust_trait "num_traits::identities::One"
  (parentClauses := ["coreopsarithMulInst"])]
structure num_traits.identities.One (Self : Type) where
  coreopsarithMulInst : core.ops.arith.Mul Self Self Self
  one : Result Self

/-- Trait declaration: [num_traits::identities::Zero]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-traits-0.2.19/src/identities.rs', lines 12:0-12:48
    Name pattern: [num_traits::identities::Zero]
    Visibility: public -/
@[rust_trait "num_traits::identities::Zero"
  (parentClauses := ["coreopsarithAddInst"])]
structure num_traits.identities.Zero (Self : Type) where
  coreopsarithAddInst : core.ops.arith.Add Self Self Self
  zero : Result Self
  is_zero : Self → Result Bool

/-- Trait declaration: [num_traits::Num]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-traits-0.2.19/src/lib.rs', lines 67:0-67:46
    Name pattern: [num_traits::Num]
    Visibility: public -/
@[rust_trait "num_traits::Num"
  (parentClauses := ["corecmpPartialEqInst", "identitiesZeroInst", "identitiesOneInst", "NumOpsInst"])]
structure num_traits.Num (Self : Type) (Self_FromStrRadixErr : Type) where
  corecmpPartialEqInst : core.cmp.PartialEq Self Self
  identitiesZeroInst : num_traits.identities.Zero Self
  identitiesOneInst : num_traits.identities.One Self
  NumOpsInst : num_traits.NumOps Self Self Self
  from_str_radix : Str → Std.U32 → Result (core.result.Result Self
    Self_FromStrRadixErr)

/-- Trait declaration: [num_integer::Integer]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-integer-0.1.46/src/lib.rs', lines 33:0-33:54
    Name pattern: [num_integer::Integer]
    Visibility: public -/
@[rust_trait "num_integer::Integer"
  (parentClauses := ["num_traitsNumInst", "corecmpPartialOrdInst", "corecmpOrdInst", "corecmpEqInst"])]
structure num_integer.Integer (Self : Type) (Self_Clause0_FromStrRadixErr :
  Type) where
  num_traitsNumInst : num_traits.Num Self Self_Clause0_FromStrRadixErr
  corecmpPartialOrdInst : core.cmp.PartialOrd Self Self
  corecmpOrdInst : core.cmp.Ord Self
  corecmpEqInst : core.cmp.Eq Self
  div_floor : Self → Self → Result Self
  mod_floor : Self → Self → Result Self
  gcd : Self → Self → Result Self
  lcm : Self → Self → Result Self
  is_multiple_of : Self → Self → Result Bool
  is_even : Self → Result Bool
  is_odd : Self → Result Bool
  div_rem : Self → Self → Result (Self × Self)

/-- Trait declaration: [num_traits::sign::Signed]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-traits-0.2.19/src/sign.rs', lines 8:0-8:50
    Name pattern: [num_traits::sign::Signed]
    Visibility: public -/
@[rust_trait "num_traits::sign::Signed"
  (parentClauses := ["NumInst", "coreopsarithNegInst"])]
structure num_traits.sign.Signed (Self : Type) (Self_Clause0_FromStrRadixErr :
  Type) where
  NumInst : num_traits.Num Self Self_Clause0_FromStrRadixErr
  coreopsarithNegInst : core.ops.arith.Neg Self Self
  abs : Self → Result Self
  abs_sub : Self → Self → Result Self
  signum : Self → Result Self
  is_positive : Self → Result Bool
  is_negative : Self → Result Bool

/-- [modinverse::egcd]:
    Source: 'src/lib.rs', lines 58:0-72:1
    Visibility: public -/
def egcd
  {T : Type} {Clause1_Clause0_FromStrRadixErr : Type}
  {Clause2_Clause0_FromStrRadixErr : Type} (corecloneCloneInst :
  core.clone.Clone T) (num_integerIntegerInst : num_integer.Integer T
  Clause1_Clause0_FromStrRadixErr) (num_traitssignSignedInst :
  num_traits.sign.Signed T Clause2_Clause0_FromStrRadixErr) (a : T) (b : T) :
  Result (T × T × T)
  := do
  sorry

/-- [modinverse::mul_mod_u64]:
    Source: 'src/lib.rs', lines 265:0-267:1 -/
def mul_mod_u64
  (a : Std.U64) (b : Std.U64) (m : Std.U64) : Result Std.U64 := do
  let i ← lift (UScalar.cast .U128 a)
  let i1 ← lift (UScalar.cast .U128 b)
  let i2 ← i * i1
  let i3 ← lift (UScalar.cast .U128 m)
  let i4 ← i2 % i3
  ok (UScalar.cast .U64 i4)

/-- [modinverse::egcd_u64]: loop 0:
    Source: 'src/lib.rs', lines 105:4-112:5
    Visibility: public -/
@[rust_loop]
def egcd_u64_loop
  (b : Std.U64) (r : Std.U64) (r_next : Std.U64) (s : Std.U64)
  (s_next : Std.U64) :
  Result (Std.U64 × Std.U64)
  := do
  if r_next != 0#u64
  then
    let q ← r / r_next
    let rem ← r % r_next
    let qs ← mul_mod_u64 q s_next b
    if s >= qs
    then let s_new ← s - qs
         egcd_u64_loop b r_next rem s_next s_new
    else
      let i ← b - qs
      let s_new ← i + s
      egcd_u64_loop b r_next rem s_next s_new
  else ok (r, s)
partial_fixpoint

/-- [modinverse::egcd_u64]:
    Source: 'src/lib.rs', lines 93:0-124:1
    Visibility: public -/
def egcd_u64
  (a : Std.U64) (b : Std.U64) : Result (Std.U64 × Std.I128 × Std.I128) := do
  if b = 0#u64
  then ok (a, 1#i128, 0#i128)
  else
    if b = 1#u64
    then ok (1#u64, 0#i128, 1#i128)
    else
      let r_next ← a % b
      let (r, s) ← egcd_u64_loop b b r_next 0#u64 1#u64
      if s = 0#u64
      then ok (r, 0#i128, 1#i128)
      else
        let i ← lift (UScalar.cast .U128 a)
        let i1 ← lift (UScalar.cast .U128 s)
        let i2 ← i * i1
        let i3 ← lift (UScalar.cast .U128 r)
        let num ← i2 - i3
        let i4 ← lift (UScalar.hcast .I128 s)
        let i5 ← lift (UScalar.cast .U128 b)
        let i6 ← num / i5
        let i7 ← lift (UScalar.hcast .I128 i6)
        let i8 ← -. i7
        ok (r, i4, i8)

/-- Trait declaration: [modinverse::ModInverse]
    Source: 'src/lib.rs', lines 229:0-231:1
    Visibility: public -/
structure ModInverse (Self : Type) where
  modinverse : Self → Self → Result (Option Self)

/-- [modinverse::modinverse]:
    Source: 'src/lib.rs', lines 241:0-243:1
    Visibility: public -/
def modinverse
  {T : Type} (ModInverseInst : ModInverse T) (a : T) (m : T) :
  Result (Option T)
  := do
  ModInverseInst.modinverse a m

/-- [modinverse::mul_mod_u8]:
    Source: 'src/lib.rs', lines 256:0-258:1 -/
def mul_mod_u8 (a : Std.U8) (b : Std.U8) (m : Std.U8) : Result Std.U8 := do
  let i ← lift (UScalar.cast .U16 a)
  let i1 ← lift (UScalar.cast .U16 b)
  let i2 ← i * i1
  let i3 ← lift (UScalar.cast .U16 m)
  let i4 ← i2 % i3
  ok (UScalar.cast .U8 i4)

/-- [modinverse::mul_mod_u16]:
    Source: 'src/lib.rs', lines 259:0-261:1 -/
def mul_mod_u16
  (a : Std.U16) (b : Std.U16) (m : Std.U16) : Result Std.U16 := do
  let i ← lift (UScalar.cast .U32 a)
  let i1 ← lift (UScalar.cast .U32 b)
  let i2 ← i * i1
  let i3 ← lift (UScalar.cast .U32 m)
  let i4 ← i2 % i3
  ok (UScalar.cast .U16 i4)

/-- [modinverse::mul_mod_u32]:
    Source: 'src/lib.rs', lines 262:0-264:1 -/
def mul_mod_u32
  (a : Std.U32) (b : Std.U32) (m : Std.U32) : Result Std.U32 := do
  let i ← lift (UScalar.cast .U64 a)
  let i1 ← lift (UScalar.cast .U64 b)
  let i2 ← i * i1
  let i3 ← lift (UScalar.cast .U64 m)
  let i4 ← i2 % i3
  ok (UScalar.cast .U32 i4)

/-- [modinverse::modinverse_u8]: loop 0:
    Source: 'src/lib.rs', lines 283:12-290:13 -/
@[rust_loop]
def modinverse_u8_loop
  (m : Std.U8) (r : Std.U8) (r_next : Std.U8) (s : Std.U8) (s_next : Std.U8) :
  Result (Std.U8 × Std.U8)
  := do
  if r_next != 0#u8
  then
    let q ← r / r_next
    let rem ← r % r_next
    let qs ← mul_mod_u8 q s_next m
    if s >= qs
    then let s_new ← s - qs
         modinverse_u8_loop m r_next rem s_next s_new
    else
      let i ← m - qs
      let s_new ← i + s
      modinverse_u8_loop m r_next rem s_next s_new
  else ok (r, s)
partial_fixpoint

/-- [modinverse::modinverse_u8]:
    Source: 'src/lib.rs', lines 274:8-296:9 -/
def modinverse_u8 (a : Std.U8) (m : Std.U8) : Result (Option Std.U8) := do
  if m = 0#u8
  then ok none
  else
    if m = 1#u8
    then ok (some 0#u8)
    else
      let r_next ← a % m
      let (r, s) ← modinverse_u8_loop m m r_next 0#u8 1#u8
      if r = 1#u8
      then ok (some s)
      else ok none

/-- [modinverse::modinverse_u16]: loop 0:
    Source: 'src/lib.rs', lines 283:12-290:13 -/
@[rust_loop]
def modinverse_u16_loop
  (m : Std.U16) (r : Std.U16) (r_next : Std.U16) (s : Std.U16)
  (s_next : Std.U16) :
  Result (Std.U16 × Std.U16)
  := do
  if r_next != 0#u16
  then
    let q ← r / r_next
    let rem ← r % r_next
    let qs ← mul_mod_u16 q s_next m
    if s >= qs
    then let s_new ← s - qs
         modinverse_u16_loop m r_next rem s_next s_new
    else
      let i ← m - qs
      let s_new ← i + s
      modinverse_u16_loop m r_next rem s_next s_new
  else ok (r, s)
partial_fixpoint

/-- [modinverse::modinverse_u16]:
    Source: 'src/lib.rs', lines 274:8-296:9 -/
def modinverse_u16 (a : Std.U16) (m : Std.U16) : Result (Option Std.U16) := do
  if m = 0#u16
  then ok none
  else
    if m = 1#u16
    then ok (some 0#u16)
    else
      let r_next ← a % m
      let (r, s) ← modinverse_u16_loop m m r_next 0#u16 1#u16
      if r = 1#u16
      then ok (some s)
      else ok none

/-- [modinverse::modinverse_u32]: loop 0:
    Source: 'src/lib.rs', lines 283:12-290:13 -/
@[rust_loop]
def modinverse_u32_loop
  (m : Std.U32) (r : Std.U32) (r_next : Std.U32) (s : Std.U32)
  (s_next : Std.U32) :
  Result (Std.U32 × Std.U32)
  := do
  if r_next != 0#u32
  then
    let q ← r / r_next
    let rem ← r % r_next
    let qs ← mul_mod_u32 q s_next m
    if s >= qs
    then let s_new ← s - qs
         modinverse_u32_loop m r_next rem s_next s_new
    else
      let i ← m - qs
      let s_new ← i + s
      modinverse_u32_loop m r_next rem s_next s_new
  else ok (r, s)
partial_fixpoint

/-- [modinverse::modinverse_u32]:
    Source: 'src/lib.rs', lines 274:8-296:9 -/
def modinverse_u32 (a : Std.U32) (m : Std.U32) : Result (Option Std.U32) := do
  if m = 0#u32
  then ok none
  else
    if m = 1#u32
    then ok (some 0#u32)
    else
      let r_next ← a % m
      let (r, s) ← modinverse_u32_loop m m r_next 0#u32 1#u32
      if r = 1#u32
      then ok (some s)
      else ok none

/-- [modinverse::modinverse_u64]: loop 0:
    Source: 'src/lib.rs', lines 283:12-290:13 -/
@[rust_loop]
def modinverse_u64_loop
  (m : Std.U64) (r : Std.U64) (r_next : Std.U64) (s : Std.U64)
  (s_next : Std.U64) :
  Result (Std.U64 × Std.U64)
  := do
  if r_next != 0#u64
  then
    let q ← r / r_next
    let rem ← r % r_next
    let qs ← mul_mod_u64 q s_next m
    if s >= qs
    then let s_new ← s - qs
         modinverse_u64_loop m r_next rem s_next s_new
    else
      let i ← m - qs
      let s_new ← i + s
      modinverse_u64_loop m r_next rem s_next s_new
  else ok (r, s)
partial_fixpoint

/-- [modinverse::modinverse_u64]:
    Source: 'src/lib.rs', lines 274:8-296:9 -/
def modinverse_u64 (a : Std.U64) (m : Std.U64) : Result (Option Std.U64) := do
  if m = 0#u64
  then ok none
  else
    if m = 1#u64
    then ok (some 0#u64)
    else
      let r_next ← a % m
      let (r, s) ← modinverse_u64_loop m m r_next 0#u64 1#u64
      if r = 1#u64
      then ok (some s)
      else ok none

/-- [modinverse::add_mod_u128]:
    Source: 'src/lib.rs', lines 382:0-389:1 -/
def add_mod_u128
  (a : Std.U128) (b : Std.U128) (m : Std.U128) : Result Std.U128 := do
  let room ← m - a
  if b < room
  then a + b
  else b - room

/-- [modinverse::mul_mod_u128]: loop 0:
    Source: 'src/lib.rs', lines 371:4-377:5 -/
@[rust_loop]
def mul_mod_u128_loop
  (a : Std.U128) (b : Std.U128) (m : Std.U128) (result : Std.U128) :
  Result Std.U128
  := do
  if b > 0#u128
  then
    let i ← lift (b &&& 1#u128)
    let result1 ← if i = 1#u128
                    then add_mod_u128 result a m
                    else ok result
    let a1 ← add_mod_u128 a a m
    let b1 ← b >>> 1#i32
    mul_mod_u128_loop a1 b1 m result1
  else ok result
partial_fixpoint

/-- [modinverse::mul_mod_u128]:
    Source: 'src/lib.rs', lines 368:0-379:1 -/
def mul_mod_u128
  (a : Std.U128) (b : Std.U128) (m : Std.U128) : Result Std.U128 := do
  let a1 ← a % m
  mul_mod_u128_loop a1 b m 0#u128

/-- [modinverse::modinverse_u128]: loop 0:
    Source: 'src/lib.rs', lines 283:12-290:13 -/
@[rust_loop]
def modinverse_u128_loop
  (m : Std.U128) (r : Std.U128) (r_next : Std.U128) (s : Std.U128)
  (s_next : Std.U128) :
  Result (Std.U128 × Std.U128)
  := do
  if r_next != 0#u128
  then
    let q ← r / r_next
    let rem ← r % r_next
    let qs ← mul_mod_u128 q s_next m
    if s >= qs
    then let s_new ← s - qs
         modinverse_u128_loop m r_next rem s_next s_new
    else
      let i ← m - qs
      let s_new ← i + s
      modinverse_u128_loop m r_next rem s_next s_new
  else ok (r, s)
partial_fixpoint

/-- [modinverse::modinverse_u128]:
    Source: 'src/lib.rs', lines 274:8-296:9 -/
def modinverse_u128
  (a : Std.U128) (m : Std.U128) : Result (Option Std.U128) := do
  if m = 0#u128
  then ok none
  else
    if m = 1#u128
    then ok (some 0#u128)
    else
      let r_next ← a % m
      let (r, s) ← modinverse_u128_loop m m r_next 0#u128 1#u128
      if r = 1#u128
      then ok (some s)
      else ok none

/-- [modinverse::{impl modinverse::ModInverse for u8}::modinverse]:
    Source: 'src/lib.rs', lines 310:12-312:13
    Visibility: public -/
def U8.Insts.ModinverseModInverse.modinverse
  (self : Std.U8) (m : Std.U8) : Result (Option Std.U8) := do
  modinverse_u8 self m

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for u8}]
    Source: 'src/lib.rs', lines 309:8-313:9 -/
@[reducible]
def U8.Insts.ModinverseModInverse : ModInverse Std.U8 := {
  modinverse := U8.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for u16}::modinverse]:
    Source: 'src/lib.rs', lines 310:12-312:13
    Visibility: public -/
def U16.Insts.ModinverseModInverse.modinverse
  (self : Std.U16) (m : Std.U16) : Result (Option Std.U16) := do
  modinverse_u16 self m

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for u16}]
    Source: 'src/lib.rs', lines 309:8-313:9 -/
@[reducible]
def U16.Insts.ModinverseModInverse : ModInverse Std.U16 := {
  modinverse := U16.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for u32}::modinverse]:
    Source: 'src/lib.rs', lines 310:12-312:13
    Visibility: public -/
def U32.Insts.ModinverseModInverse.modinverse
  (self : Std.U32) (m : Std.U32) : Result (Option Std.U32) := do
  modinverse_u32 self m

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for u32}]
    Source: 'src/lib.rs', lines 309:8-313:9 -/
@[reducible]
def U32.Insts.ModinverseModInverse : ModInverse Std.U32 := {
  modinverse := U32.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for u64}::modinverse]:
    Source: 'src/lib.rs', lines 310:12-312:13
    Visibility: public -/
def U64.Insts.ModinverseModInverse.modinverse
  (self : Std.U64) (m : Std.U64) : Result (Option Std.U64) := do
  modinverse_u64 self m

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for u64}]
    Source: 'src/lib.rs', lines 309:8-313:9 -/
@[reducible]
def U64.Insts.ModinverseModInverse : ModInverse Std.U64 := {
  modinverse := U64.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for u128}::modinverse]:
    Source: 'src/lib.rs', lines 310:12-312:13
    Visibility: public -/
def U128.Insts.ModinverseModInverse.modinverse
  (self : Std.U128) (m : Std.U128) : Result (Option Std.U128) := do
  modinverse_u128 self m

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for u128}]
    Source: 'src/lib.rs', lines 309:8-313:9 -/
@[reducible]
def U128.Insts.ModinverseModInverse : ModInverse Std.U128 := {
  modinverse := U128.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for i8}::modinverse]:
    Source: 'src/lib.rs', lines 339:12-355:13
    Visibility: public -/
def I8.Insts.ModinverseModInverse.modinverse
  (self : Std.I8) (m : Std.I8) : Result (Option Std.I8) := do
  if m = 0#i8
  then ok none
  else
    let m_abs ←
      if m < 0#i8
      then
        do
        let i ← lift (IScalar.hcast .U8 m)
        ok (core.num.U8.wrapping_sub 0#u8 i)
      else ok (IScalar.hcast .U8 m)
    let s_abs ←
      if self < 0#i8
      then
        do
        let i ← lift (IScalar.hcast .U8 self)
        ok (core.num.U8.wrapping_sub 0#u8 i)
      else ok (IScalar.hcast .U8 self)
    let a_abs ← s_abs % m_abs
    let a_u ←
      if self < 0#i8
      then if a_abs != 0#u8
           then m_abs - a_abs
           else ok a_abs
      else ok a_abs
    let o ← modinverse_u8 a_u m_abs
    match o with
    | none => ok none
    | some x => let i ← lift (UScalar.hcast .I8 x)
                ok (some i)

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for i8}]
    Source: 'src/lib.rs', lines 336:8-356:9 -/
@[reducible]
def I8.Insts.ModinverseModInverse : ModInverse Std.I8 := {
  modinverse := I8.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for i16}::modinverse]:
    Source: 'src/lib.rs', lines 339:12-355:13
    Visibility: public -/
def I16.Insts.ModinverseModInverse.modinverse
  (self : Std.I16) (m : Std.I16) : Result (Option Std.I16) := do
  if m = 0#i16
  then ok none
  else
    let m_abs ←
      if m < 0#i16
      then
        do
        let i ← lift (IScalar.hcast .U16 m)
        ok (core.num.U16.wrapping_sub 0#u16 i)
      else ok (IScalar.hcast .U16 m)
    let s_abs ←
      if self < 0#i16
      then
        do
        let i ← lift (IScalar.hcast .U16 self)
        ok (core.num.U16.wrapping_sub 0#u16 i)
      else ok (IScalar.hcast .U16 self)
    let a_abs ← s_abs % m_abs
    let a_u ←
      if self < 0#i16
      then if a_abs != 0#u16
           then m_abs - a_abs
           else ok a_abs
      else ok a_abs
    let o ← modinverse_u16 a_u m_abs
    match o with
    | none => ok none
    | some x => let i ← lift (UScalar.hcast .I16 x)
                ok (some i)

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for i16}]
    Source: 'src/lib.rs', lines 336:8-356:9 -/
@[reducible]
def I16.Insts.ModinverseModInverse : ModInverse Std.I16 := {
  modinverse := I16.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for i32}::modinverse]:
    Source: 'src/lib.rs', lines 339:12-355:13
    Visibility: public -/
def I32.Insts.ModinverseModInverse.modinverse
  (self : Std.I32) (m : Std.I32) : Result (Option Std.I32) := do
  if m = 0#i32
  then ok none
  else
    let m_abs ←
      if m < 0#i32
      then
        do
        let i ← lift (IScalar.hcast .U32 m)
        ok (core.num.U32.wrapping_sub 0#u32 i)
      else ok (IScalar.hcast .U32 m)
    let s_abs ←
      if self < 0#i32
      then
        do
        let i ← lift (IScalar.hcast .U32 self)
        ok (core.num.U32.wrapping_sub 0#u32 i)
      else ok (IScalar.hcast .U32 self)
    let a_abs ← s_abs % m_abs
    let a_u ←
      if self < 0#i32
      then if a_abs != 0#u32
           then m_abs - a_abs
           else ok a_abs
      else ok a_abs
    let o ← modinverse_u32 a_u m_abs
    match o with
    | none => ok none
    | some x => let i ← lift (UScalar.hcast .I32 x)
                ok (some i)

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for i32}]
    Source: 'src/lib.rs', lines 336:8-356:9 -/
@[reducible]
def I32.Insts.ModinverseModInverse : ModInverse Std.I32 := {
  modinverse := I32.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for i64}::modinverse]:
    Source: 'src/lib.rs', lines 339:12-355:13
    Visibility: public -/
def I64.Insts.ModinverseModInverse.modinverse
  (self : Std.I64) (m : Std.I64) : Result (Option Std.I64) := do
  if m = 0#i64
  then ok none
  else
    let m_abs ←
      if m < 0#i64
      then
        do
        let i ← lift (IScalar.hcast .U64 m)
        ok (core.num.U64.wrapping_sub 0#u64 i)
      else ok (IScalar.hcast .U64 m)
    let s_abs ←
      if self < 0#i64
      then
        do
        let i ← lift (IScalar.hcast .U64 self)
        ok (core.num.U64.wrapping_sub 0#u64 i)
      else ok (IScalar.hcast .U64 self)
    let a_abs ← s_abs % m_abs
    let a_u ←
      if self < 0#i64
      then if a_abs != 0#u64
           then m_abs - a_abs
           else ok a_abs
      else ok a_abs
    let o ← modinverse_u64 a_u m_abs
    match o with
    | none => ok none
    | some x => let i ← lift (UScalar.hcast .I64 x)
                ok (some i)

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for i64}]
    Source: 'src/lib.rs', lines 336:8-356:9 -/
@[reducible]
def I64.Insts.ModinverseModInverse : ModInverse Std.I64 := {
  modinverse := I64.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for i128}::modinverse]:
    Source: 'src/lib.rs', lines 339:12-355:13
    Visibility: public -/
def I128.Insts.ModinverseModInverse.modinverse
  (self : Std.I128) (m : Std.I128) : Result (Option Std.I128) := do
  if m = 0#i128
  then ok none
  else
    let m_abs ←
      if m < 0#i128
      then
        do
        let i ← lift (IScalar.hcast .U128 m)
        ok (core.num.U128.wrapping_sub 0#u128 i)
      else ok (IScalar.hcast .U128 m)
    let s_abs ←
      if self < 0#i128
      then
        do
        let i ← lift (IScalar.hcast .U128 self)
        ok (core.num.U128.wrapping_sub 0#u128 i)
      else ok (IScalar.hcast .U128 self)
    let a_abs ← s_abs % m_abs
    let a_u ←
      if self < 0#i128
      then if a_abs != 0#u128
           then m_abs - a_abs
           else ok a_abs
      else ok a_abs
    let o ← modinverse_u128 a_u m_abs
    match o with
    | none => ok none
    | some x => let i ← lift (UScalar.hcast .I128 x)
                ok (some i)

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for i128}]
    Source: 'src/lib.rs', lines 336:8-356:9 -/
@[reducible]
def I128.Insts.ModinverseModInverse : ModInverse Std.I128 := {
  modinverse := I128.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for usize}::modinverse]:
    Source: 'src/lib.rs', lines 431:4-436:5
    Visibility: public -/
def Usize.Insts.ModinverseModInverse.modinverse
  (self : Std.Usize) (m : Std.Usize) : Result (Option Std.Usize) := do
  let i ← lift (UScalar.cast .U64 self)
  let i1 ← lift (UScalar.cast .U64 m)
  let o ← U64.Insts.ModinverseModInverse.modinverse i i1
  match o with
  | none => ok none
  | some x => let i2 ← lift (UScalar.cast .Usize x)
              ok (some i2)

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for usize}]
    Source: 'src/lib.rs', lines 428:0-437:1 -/
@[reducible]
def Usize.Insts.ModinverseModInverse : ModInverse Std.Usize := {
  modinverse := Usize.Insts.ModinverseModInverse.modinverse
}

/-- [modinverse::{impl modinverse::ModInverse for isize}::modinverse]:
    Source: 'src/lib.rs', lines 465:4-470:5
    Visibility: public -/
def Isize.Insts.ModinverseModInverse.modinverse
  (self : Std.Isize) (m : Std.Isize) : Result (Option Std.Isize) := do
  let i ← lift (IScalar.cast .I64 self)
  let i1 ← lift (IScalar.cast .I64 m)
  let o ← I64.Insts.ModinverseModInverse.modinverse i i1
  match o with
  | none => ok none
  | some x => let i2 ← lift (IScalar.cast .Isize x)
              ok (some i2)

/-- Trait implementation: [modinverse::{impl modinverse::ModInverse for isize}]
    Source: 'src/lib.rs', lines 462:0-471:1 -/
@[reducible]
def Isize.Insts.ModinverseModInverse : ModInverse Std.Isize := {
  modinverse := Isize.Insts.ModinverseModInverse.modinverse
}

end modinverse
